version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run unit tests
          command: python Test.py

  build-docker-image:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t your-dockerhub-username/invoicer-app:latest .
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker image to Docker Hub
          command: docker push your-dockerhub-username/invoicer-app:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - build-docker-image:
          requires:
            - build
